In [19]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

#Technical Requirements

#Groupby Mechanics

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('/content/gdrive/My Drive/01.google-colab/61.AIStudy/data/automobileEDA.csv')

In [25]:
# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [26]:
# df.head()
df

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,0.909722,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,0.919444,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,0.922222,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,std,four,sedan,rwd,front,109.1,0.907256,0.956944,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0,10.217391,Medium,0,1
197,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,0.907256,0.955556,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0,12.368421,High,0,1
198,-1,95,volvo,std,four,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0,13.055556,Medium,0,1
199,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,9.038462,Medium,1,0
200,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,0.907256,0.956944,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,12.368421,Medium,0,1

the output is as follows:\
1)symboling 2)normalized-losses 3)make 4)aspiration 5)num-of-doors 6)body-style 7)drive-wheels 8)engine-location 9)wheel-base 10)length
11)width 12)height 13)curb-weight 14)engine-type 15)num-of-cylinders 16)engine-size 17)fuel-system 18)bore 19)stroke 20)compression-ratio 21)horsepower 22)peak-rpm 23)city-mpg 24)highway-mpg 25)price 26)city-L/100km 27)horsepower-binned 28)diesel 29)gas

In [27]:
df.groupby('body-style').groups.keys()

dict_keys(['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'])

In [28]:
style = df.groupby('body-style')
style.get_group("convertible")

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,0.890278,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
69,3,142,mercedes-benz,std,two,convertible,rwd,front,96.6,0.866410,0.979167,50.8,3685,ohcv,eight,234,mpfi,3.46,3.10,8.3,155.0,4750.0,16,18,35056.0,14.687500,Medium,0,1
125,3,122,porsche,std,two,convertible,rwd,rear,89.5,0.811629,0.902778,51.6,2800,ohcf,six,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,37028.0,13.823529,High,0,1
168,2,134,toyota,std,two,convertible,rwd,front,98.4,0.846708,0.911111,53.0,2975,ohc,four,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,17669.0,9.791667,Medium,0,1
185,3,122,volkswagen,std,two,convertible,fwd,front,94.5,0.765497,0.891667,55.6,2254,ohc,four,109,mpfi,3.19,3.40,8.5,90.0,5500.0,24,29,11595.0,9.791667,Low,0,1

#Selecting a subset of columns

In [29]:
double_grouping = df.groupby(['body-style', 'drive-wheels'])
double_grouping.first()

                          symboling  normalized-losses           make  \
body-style  drive-wheels
convertible fwd                   3                122     volkswagen
            rwd                   3                122    alfa-romero
hardtop     fwd                   2                168         nissan
            rwd                   0                 93  mercedes-benz
hatchback   4wd                   2                 83         subaru
            fwd                   2                121      chevrolet
            rwd                   1                122    alfa-romero
sedan       4wd                   2                164           audi
            fwd                   2                164           audi
            rwd                   2                192            bmw
wagon       4wd                   0                 85         subaru
            fwd                   1                122           audi
            rwd                  -1                 93  mercedes-benz

                         aspiration num-of-doors engine-location  wheel-base  \
body-style  drive-wheels
convertible fwd                 std          two           front        94.5
            rwd                 std          two           front        88.6
hardtop     fwd                 std          two           front        95.1
            rwd               turbo          two           front       106.7
hatchback   4wd                 std          two           front        93.3
            fwd                 std          two           front        88.4
            rwd                 std          two           front        94.5
sedan       4wd                 std         four           front        99.4
            fwd                 std         four           front        99.8
            rwd                 std          two           front       101.2
wagon       4wd                 std         four           front        96.9
            fwd                 std         four           front       105.8
            rwd               turbo         four           front       110.0

                            length     width  height  curb-weight engine-type  \
body-style  drive-wheels
convertible fwd           0.765497  0.891667    55.6         2254         ohc
            rwd           0.811148  0.890278    48.8         2548        dohc
hardtop     fwd           0.780394  0.886111    53.3         2008         ohc
            rwd           0.901009  0.976389    54.9         3495         ohc
hatchback   4wd           0.755887  0.886111    55.7         2240        ohcf
            fwd           0.678039  0.837500    53.2         1488           l
            rwd           0.822681  0.909722    52.4         2823        ohcv
sedan       4wd           0.848630  0.922222    54.3         2824         ohc
            fwd           0.848630  0.919444    54.3         2337         ohc
            rwd           0.849592  0.900000    54.3         2395         ohc
wagon       4wd           0.834214  0.908333    54.9         2420        ohcf
            fwd           0.925997  0.991667    55.7         2954         ohc
            rwd           0.917347  0.976389    58.7         3750         ohc

                         num-of-cylinders  engine-size fuel-system  bore  \
body-style  drive-wheels
convertible fwd                      four          109        mpfi  3.19
            rwd                      four          130        mpfi  3.47
hardtop     fwd                      four           97        2bbl  3.15
            rwd                      five          183         idi  3.58
hatchback   4wd                      four          108        2bbl  3.62
            fwd                     three           61        2bbl  2.91
            rwd                       six          152        mpfi  2.68
sedan       4wd                      five          136        mpfi  3.19
            fwd                      four          109        mpfi  3.19
            rwd                      four          108        mpfi  3.50
wagon       4wd                      four          108        2bbl  3.62
            fwd                      five          136        mpfi  3.19
            rwd                      five          183         idi  3.58

                          stroke  compression-ratio  horsepower  peak-rpm  \
body-style  drive-wheels
convertible fwd             3.40                8.5        90.0    5500.0
            rwd             2.68                9.0       111.0    5000.0
hardtop     fwd             3.29                9.4        69.0    5200.0
            rwd             3.64               21.5       123.0    4350.0
hatchback   4wd             2.64                8.7        73.0    4400.0
            fwd             3.03                9.5        48.0    5100.0
            rwd             3.47                9.0       154.0    5000.0
sedan       4wd             3.40                8.0       115.0    5500.0
            fwd             3.40               10.0       102.0    5500.0
            rwd             2.80                8.8       101.0    5800.0
wagon       4wd             2.64                9.0        82.0    4800.0
            fwd             3.40                8.5       110.0    5500.0
            rwd             3.64               21.5       123.0    4350.0

                          city-mpg  highway-mpg    price  city-L/100km  \
body-style  drive-wheels
convertible fwd                 24           29  11595.0      9.791667
            rwd                 21           27  13495.0     11.190476
hardtop     fwd                 31           37   8249.0      7.580645
            rwd                 22           25  28176.0     10.681818
hatchback   4wd                 26           31   7603.0      9.038462
            fwd                 47           53   5151.0      5.000000
            rwd                 19           26  16500.0     12.368421
sedan       4wd                 18           22  17450.0     13.055556
            fwd                 24           30  13950.0      9.791667
            rwd                 23           29  16430.0     10.217391
wagon       4wd                 23           29   8013.0     10.217391
            fwd                 19           25  18920.0     12.368421
            rwd                 22           25  28248.0     10.681818

                         horsepower-binned  diesel  gas
body-style  drive-wheels
convertible fwd                        Low       0    1
            rwd                     Medium       0    1
hardtop     fwd                        Low       0    1
            rwd                     Medium       1    0
hatchback   4wd                        Low       0    1
            fwd                        Low       0    1
            rwd                     Medium       0    1
sedan       4wd                     Medium       0    1
            fwd                     Medium       0    1
            rwd                        Low       0    1
wagon       4wd                        Low       0    1
            fwd                     Medium       0    1
            rwd                     Medium       1    0

#Max and Min

In [30]:
style['normalized-losses'].max()
#style['normalized-losses'].min()

body-style
convertible    142
hardtop        168
hatchback      256
sedan          192
wagon          122
Name: normalized-losses, dtype: int64

#Mean

In [31]:
style.mean()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
body-style,,,,,,,,,,,,,,,,,,,
convertible,2.833333,127.333333,92.700000,0.818757,0.910880,51.433333,2801.666667,157.166667,3.491667,3.043333,8.933333,131.666667,5158.333333,20.500000,26.000000,21890.500000,11.745886,0.000000,1.000000
hardtop,1.875000,128.625000,98.500000,0.850252,0.925174,52.850000,2810.625000,176.250000,3.608750,3.322500,10.725000,142.250000,5031.250000,21.625000,27.250000,22208.500000,11.508780,0.125000,0.875000
hatchback,1.617647,130.897059,95.435294,0.799078,0.904228,52.133824,2322.852941,112.852941,3.236015,3.280312,9.042941,97.768473,5219.490727,26.602941,32.382353,9957.441176,9.434906,0.014706,0.985294
sedan,0.329787,120.893617,100.750000,0.855583,0.921070,54.387234,2625.893617,131.691489,3.345106,3.270638,10.965957,103.808511,5075.000000,25.053191,30.574468,14459.755319,10.027994,0.159574,0.840426
wagon,-0.160000,98.560000,102.156000,0.871235,0.920222,56.728000,2784.240000,123.840000,3.406400,3.175600,10.316000,98.010246,5019.014778,24.040000,28.720000,12371.960000,10.080906,0.120000,0.880000

In [32]:
# get mean of each column of specific group
style.get_group("convertible").mean()

symboling                2.833333
normalized-losses      127.333333
wheel-base              92.700000
length                   0.818757
width                    0.910880
height                  51.433333
curb-weight           2801.666667
engine-size            157.166667
bore                     3.491667
stroke                   3.043333
compression-ratio        8.933333
horsepower             131.666667
peak-rpm              5158.333333
city-mpg                20.500000
highway-mpg             26.000000
price                21890.500000
city-L/100km            11.745886
diesel                   0.000000
gas                      1.000000
dtype: float64

In [33]:
# get the number of symboling/records in each group
style['symboling'].count()

body-style
convertible     6
hardtop         8
hatchback      68
sedan          94
wagon          25
Name: symboling, dtype: int64

#Data Aggregation

In [34]:
# new dataframe that consist length, width, height, curb-weight and price 
new_dataset = df.filter(["length", "width", "height", "curb-weight", "price"], axis=1)
new_dataset

       length     width  height  curb-weight    price
0    0.811148  0.890278    48.8         2548  13495.0
1    0.811148  0.890278    48.8         2548  16500.0
2    0.822681  0.909722    52.4         2823  16500.0
3    0.848630  0.919444    54.3         2337  13950.0
4    0.848630  0.922222    54.3         2824  17450.0
..        ...       ...     ...          ...      ...
196  0.907256  0.956944    55.5         2952  16845.0
197  0.907256  0.955556    55.5         3049  19045.0
198  0.907256  0.956944    55.5         3012  21485.0
199  0.907256  0.956944    55.5         3217  22470.0
200  0.907256  0.956944    55.5         3062  22625.0

[201 rows x 5 columns]

In [35]:
# apllying single aggregation for mean over the columns
new_dataset.agg("mean", axis="rows")

length             0.837102
width              0.915126
height            53.766667
curb-weight     2555.666667
price          13207.129353
dtype: float64

In [36]:
# new_dataset.agg(['sum', 'min'])
new_dataset.agg(['sum', 'min', 'max'])

         length       width   height  curb-weight      price
sum  168.257568  183.940278  10807.1       513689  2654633.0
min    0.678039    0.837500     47.8         1488     5118.0
max    1.000000    1.000000     59.8         4066    45400.0

In [37]:
# find aggregation for these columns
new_dataset.aggregate({"length":['sum', 'min'], "width":['max', 'min'], "height":['min', 'sum'], "curb-weight":['sum']})

         length   width   height  curb-weight
max         NaN  1.0000      NaN          NaN
min    0.678039  0.8375     47.8          NaN
sum  168.257568     NaN  10807.1     513689.0

#Group-Wise Operation

In [38]:
# group the data frame df by body-style and drive-wheels and extract stats from each group
df.groupby(["body-style", "drive-wheels"]).agg({\
                                                'height':min,\
                                                'length':max,\
                                                'price':'mean'})

                          height    length         price
body-style  drive-wheels
convertible fwd             55.6  0.765497  11595.000000
            rwd             48.8  0.866410  23949.600000
hardtop     fwd             53.3  0.780394   8249.000000
            rwd             51.6  0.957232  24202.714286
hatchback   4wd             55.7  0.755887   7603.000000
            fwd             49.4  0.896684   8396.387755
            rwd             49.6  0.881788  14337.777778
sedan       4wd             54.3  0.848630  12647.333333
            fwd             50.6  0.925997   9811.800000
            rwd             47.8  1.000000  21711.833333
wagon       4wd             54.9  0.834214   9095.750000
            fwd             53.0  0.925997   9997.333333
            rwd             54.1  0.955790  16994.222222

In [39]:
# create dictionary of aggregations
aggregations=({\
               'height':min,\
               'length':max,\
               'price':'mean'})
# implementing aggregation in groups
df.groupby(["body-style", "drive-wheels"]).agg(aggregations)

                          height    length         price
body-style  drive-wheels
convertible fwd             55.6  0.765497  11595.000000
            rwd             48.8  0.866410  23949.600000
hardtop     fwd             53.3  0.780394   8249.000000
            rwd             51.6  0.957232  24202.714286
hatchback   4wd             55.7  0.755887   7603.000000
            fwd             49.4  0.896684   8396.387755
            rwd             49.6  0.881788  14337.777778
sedan       4wd             54.3  0.848630  12647.333333
            fwd             50.6  0.925997   9811.800000
            rwd             47.8  1.000000  21711.833333
wagon       4wd             54.9  0.834214   9095.750000
            fwd             53.0  0.925997   9997.333333
            rwd             54.1  0.955790  16994.222222

In [40]:
# import the numpy library as np
import numpy as np

# using numpy libraries for operations
df.groupby(["body-style", "drive-wheels"])["price"].agg([np.sum, np.mean, np.std])

                               sum          mean           std
body-style  drive-wheels
convertible fwd            11595.0  11595.000000           NaN
            rwd           119748.0  23949.600000  11165.099700
hardtop     fwd             8249.0   8249.000000           NaN
            rwd           169419.0  24202.714286  14493.311190
hatchback   4wd             7603.0   7603.000000           NaN
            fwd           411423.0   8396.387755   3004.675695
            rwd           258080.0  14337.777778   3831.795195
sedan       4wd            37942.0  12647.333333   4280.814681
            fwd           539649.0   9811.800000   3519.517598
            rwd           781626.0  21711.833333   9194.820239
wagon       4wd            36383.0   9095.750000   1775.652063
            fwd           119968.0   9997.333333   3584.185551
            rwd           152948.0  16994.222222   4686.703313

#Renaming Grouped Aggregation Columns

In [41]:
df.groupby(\
           ["body-style", "drive-wheels"]).agg(\
                                               max_price=('price', max),\
                                               min_price=('price', min),\
                                               total_price=('price', 'mean'))

                          max_price  min_price   total_price
body-style  drive-wheels
convertible fwd             11595.0    11595.0  11595.000000
            rwd             37028.0    13495.0  23949.600000
hardtop     fwd              8249.0     8249.0   8249.000000
            rwd             45400.0     8449.0  24202.714286
hatchback   4wd              7603.0     7603.0   7603.000000
            fwd             18150.0     5118.0   8396.387755
            rwd             22018.0     8238.0  14337.777778
sedan       4wd             17450.0     9233.0  12647.333333
            fwd             23875.0     5499.0   9811.800000
            rwd             41315.0     6785.0  21711.833333
wagon       4wd             11694.0     7898.0   9095.750000
            fwd             18920.0     6918.0   9997.333333
            rwd             28248.0    12440.0  16994.222222

#Group-Wise Transformations

In [42]:
# 1. let's begin by using a simple transformation function to increase the price of each car by 10% using the lambda function:
df["price"]=df["price"].transform(lambda x:x + x/10)
df.loc[:,'price']

0      14844.5
1      18150.0
2      18150.0
3      15345.0
4      19195.0
        ...
196    18529.5
197    20949.5
198    23633.5
199    24717.0
200    24887.5
Name: price, Length: 201, dtype: float64

In [43]:
# 2. let's observe the average price of cars each grouping by body-style and drive-wheels:
df.groupby(["body-style", "drive-wheels"])["price"].transform('mean')

0      26344.560000
1      26344.560000
2      15771.555556
3      10792.980000
4      13912.066667
           ...
196    23883.016667
197    23883.016667
198    23883.016667
199    23883.016667
200    23883.016667
Name: price, Length: 201, dtype: float64

In [44]:
# 3. now, create a new column for an average price in the original dataframe:
df["average-price"]=df.groupby(["body-style", "drive-wheels"])["price"].transform('mean')

# selecting columns body-style, drive-wheels, price and average-price 
df.loc[:, ["body-style", "drive-wheels", "price", "average-price"]]

      body-style drive-wheels    price  average-price
0    convertible          rwd  14844.5   26344.560000
1    convertible          rwd  18150.0   26344.560000
2      hatchback          rwd  18150.0   15771.555556
3          sedan          fwd  15345.0   10792.980000
4          sedan          4wd  19195.0   13912.066667
..           ...          ...      ...            ...
196        sedan          rwd  18529.5   23883.016667
197        sedan          rwd  20949.5   23883.016667
198        sedan          rwd  23633.5   23883.016667
199        sedan          rwd  24717.0   23883.016667
200        sedan          rwd  24887.5   23883.016667

[201 rows x 4 columns]

#Pivot Table and Cross-Tabulations
Pivot Tables

In [45]:
# 1. let's make a pivot table of a new dataframe that consists of the body-style, drive-wheels, length, width height, curb-weight, and price columns:
new_dataset1 = df.filter(["body-style", "drive-wheels", "length", "width", "height", "curb-weight", "price"], axis=1)
# new_dataset1

# simplest pivot table with dataframe df and index body-style
# table = pd.pivot_table(new_dataset1, index=["body-style"])
# table = pd.pivot_table(new_dataset1, index=["body-style", "drive-wheels"], margins=True, margins_name="Total")
table = pd.pivot_table(new_dataset1, index=["body-style"], margins=True, margins_name="Total")
table

             curb-weight     height    length         price     width
body-style
convertible  2801.666667  51.433333  0.818757  24079.550000  0.910880
hardtop      2810.625000  52.850000  0.850252  24429.350000  0.925174
hatchback    2322.852941  52.133824  0.799078  10953.185294  0.904228
sedan        2625.893617  54.387234  0.855583  15905.730851  0.921070
wagon        2784.240000  56.728000  0.871235  13609.156000  0.920222
Total        2555.666667  53.766667  0.837102  14527.842289  0.915126

In [46]:
# 2. now, design a pivot table with the new_dataset1 dataframe and make body-style and drive-wheels as an index.

# pivot table with dataframe df and index body-style and drive-wheels
table = pd.pivot_table(new_dataset1, index=["body-style", "drive-wheels"])
table

                          curb-weight     height    length         price  \
body-style  drive-wheels
convertible fwd           2254.000000  55.600000  0.765497  12754.500000
            rwd           2911.200000  50.600000  0.829409  26344.560000
hardtop     fwd           2008.000000  53.300000  0.780394   9073.900000
            rwd           2925.285714  52.785714  0.860232  26622.985714
hatchback   4wd           2240.000000  55.700000  0.755887   8363.300000
            fwd           2181.551020  52.442857  0.787818   9236.026531
            rwd           2712.111111  51.094444  0.832132  15771.555556
sedan       4wd           2573.000000  54.300000  0.833894  13912.066667
            fwd           2313.018182  53.956364  0.828404  10792.980000
            rwd           3108.305556  55.052778  0.898913  23883.016667
wagon       4wd           2617.500000  57.000000  0.824844  10005.325000
            fwd           2464.333333  56.008333  0.843064  10997.066667
            rwd           3284.888889  57.566667  0.929414  18693.644444

                             width
body-style  drive-wheels
convertible fwd           0.891667
            rwd           0.914722
hardtop     fwd           0.886111
            rwd           0.930754
hatchback   4wd           0.886111
            fwd           0.898214
            rwd           0.921605
sedan       4wd           0.912963
            fwd           0.908182
            rwd           0.941435
wagon       4wd           0.895833
            fwd           0.910185
            rwd           0.944444

In [47]:
# import numpy for aggregation function
import numpy as np

In [48]:
# new data set with few columns
new_dataset3 = df.filter(["body-style", "drive-wheels", "price"], axis=1)
# new_dataset3
print(new_dataset3.head())
print("--------------------------------------------------")
table = pd.pivot_table(new_dataset3, values='price', index=["body-style"], columns=["drive-wheels"], aggfunc=np.mean, fill_value=0)
table

    body-style drive-wheels    price
0  convertible          rwd  14844.5
1  convertible          rwd  18150.0
2    hatchback          rwd  18150.0
3        sedan          fwd  15345.0
4        sedan          4wd  19195.0
--------------------------------------------------

drive-wheels           4wd           fwd           rwd
body-style
convertible       0.000000  12754.500000  26344.560000
hardtop           0.000000   9073.900000  26622.985714
hatchback      8363.300000   9236.026531  15771.555556
sedan         13912.066667  10792.980000  23883.016667
wagon         10005.325000  10997.066667  18693.644444

In [49]:
# 3. we can also apply a different aggregation function to different columns:
table = pd.pivot_table(new_dataset1, values=['price', 'height', 'width'],\
                       index=["body-style", "drive-wheels"],\
                       aggfunc={'price':np.mean, 'height':[min,max], 'width':[min,max]},\
                       fill_value=0)
table

                         height               price     width
                            max   min          mean       max       min
body-style  drive-wheels
convertible fwd            55.6  55.6  12754.500000  0.891667  0.891667
            rwd            53.0  48.8  26344.560000  0.979167  0.890278
hardtop     fwd            53.3  53.3   9073.900000  0.886111  0.886111
            rwd            55.4  51.6  26622.985714  1.000000  0.902778
hatchback   4wd            55.7  55.7   8363.300000  0.886111  0.886111
            fwd            56.1  49.4   9236.026531  0.925000  0.837500
            rwd            54.8  49.6  15771.555556  0.948611  0.888889
sedan       4wd            54.3  54.3  13912.066667  0.922222  0.908333
            fwd            56.1  50.6  10792.980000  0.991667  0.868056
            rwd            56.7  47.8  23883.016667  0.995833  0.858333
wagon       4wd            59.1  54.9  10005.325000  0.908333  0.883333
            fwd            59.8  53.0  10997.066667  0.991667  0.883333
            rwd            58.7  54.1  18693.644444  0.976389  0.923611

#Cross-Tabulations

In [ ]:
# 1. let's use pd.crosstab() to look at how many different body styles cars are made by different makers:
pd.crosstab(df["make"], df["body-style"])

# apply margins and argins_name attribute 
# to displays the row wise and column wise sum of the cross table
pd.crosstab(df["make"], df["body-style"], margins=True, margins_name="Total Made")

In [ ]:
# 2. let's see how the data is distributed by the body-type and drive_wheels columns within the maker of car and their door type in a crosstab:
pd.crosstab([df["make"], df["num-of-doors"]], [df["body-style"], df["drive-wheels"]], margins=True, margins_name="Total Made")

body-style                 convertible     hardtop      ... wagon         Total Made
drive-wheels                       fwd rwd     fwd rwd  ...   4wd fwd rwd
make          num-of-doors                              ...
alfa-romero   two                    0   2       0   0  ...     0   0   0          3
audi          four                   0   0       0   0  ...     0   1   0          5
              two                    0   0       0   0  ...     0   0   0          1
bmw           four                   0   0       0   0  ...     0   0   0          5
              two                    0   0       0   0  ...     0   0   0          3
chevrolet     four                   0   0       0   0  ...     0   0   0          1
              two                    0   0       0   0  ...     0   0   0          2
dodge         four                   0   0       0   0  ...     0   1   0          5
              two                    0   0       0   0  ...     0   0   0          4
honda         four                   0   0       0   0  ...     0   1   0          5
              two                    0   0       0   0  ...     0   0   0          8
isuzu         four                   0   0       0   0  ...     0   0   0          1
              two                    0   0       0   0  ...     0   0   0          1
jaguar        four                   0   0       0   0  ...     0   0   0          2
              two                    0   0       0   0  ...     0   0   0          1
mazda         four                   0   0       0   0  ...     0   0   0          8
              two                    0   0       0   0  ...     0   0   0          9
mercedes-benz four                   0   0       0   0  ...     0   0   1          5
              two                    0   1       0   2  ...     0   0   0          3
mercury       two                    0   0       0   0  ...     0   0   0          1
mitsubishi    four                   0   0       0   0  ...     0   0   0          4
              two                    0   0       0   0  ...     0   0   0          9
nissan        four                   0   0       0   0  ...     0   3   0          9
              two                    0   0       1   0  ...     0   0   0          9
peugot        four                   0   0       0   0  ...     0   0   4         11
plymouth      four                   0   0       0   0  ...     0   1   0          4
              two                    0   0       0   0  ...     0   0   0          3
porsche       two                    0   1       0   2  ...     0   0   0          4
renault       four                   0   0       0   0  ...     0   1   0          1
              two                    0   0       0   0  ...     0   0   0          1
saab          four                   0   0       0   0  ...     0   0   0          3
              two                    0   0       0   0  ...     0   0   0          3
subaru        four                   0   0       0   0  ...     2   2   0          9
              two                    0   0       0   0  ...     0   0   0          3
toyota        four                   0   0       0   0  ...     2   1   1         18
              two                    0   1       0   3  ...     0   0   0         14
volkswagen    four                   0   0       0   0  ...     0   1   0          8
              two                    1   0       0   0  ...     0   0   0          4
volvo         four                   0   0       0   0  ...     0   0   3         11
Total Made                           1   5       1   7  ...     4  12   9        201

[40 rows x 14 columns]

In [51]:
# rename the columns and row index for better understanding of crosstab
pd.crosstab([df["make"], df["num-of-doors"]], [df["body-style"], df["drive-wheels"]],\
            rownames=['Auto Manufacturer', "Doors"],\
            colnames=['Body Style', "Drive Type"],\
            margins=True, margins_name="Total Made").head()

Body Style              convertible     hardtop     hatchback         sedan  \
Drive Type                      fwd rwd     fwd rwd       4wd fwd rwd   4wd
Auto Manufacturer Doors
alfa-romero       two             0   2       0   0         0   0   1     0
audi              four            0   0       0   0         0   0   0     1
                  two             0   0       0   0         0   0   0     0
bmw               four            0   0       0   0         0   0   0     0
                  two             0   0       0   0         0   0   0     0

Body Style                      wagon         Total Made
Drive Type              fwd rwd   4wd fwd rwd
Auto Manufacturer Doors
alfa-romero       two     0   0     0   0   0          3
audi              four    3   0     0   1   0          5
                  two     1   0     0   0   0          1
bmw               four    0   5     0   0   0          5
                  two     0   3     0   0   0          3

In [52]:
# 3. first. let's look at the average curb-weight of cars made by different makers with respect to their body-style by applying the mean() aggregation function to the crosstable:
# value are the column in which aggregation function is to be applied
# aggfunc is the aggregation function to be applied
# round() to round the output
pd.crosstab(df["make"], df["body-style"], values=df["curb-weight"], aggfunc='mean').round(0)

body-style     convertible  hardtop  hatchback   sedan   wagon
make
alfa-romero         2548.0      NaN     2823.0     NaN     NaN
audi                   NaN      NaN        NaN  2720.0  2954.0
bmw                    NaN      NaN        NaN  2929.0     NaN
chevrolet              NaN      NaN     1681.0  1909.0     NaN
dodge                  NaN      NaN     2132.0  2056.0  2535.0
honda                  NaN      NaN     1970.0  2289.0  2024.0
isuzu                  NaN      NaN     2734.0  2337.0     NaN
jaguar                 NaN      NaN        NaN  4027.0     NaN
mazda                  NaN      NaN     2254.0  2361.0     NaN
mercedes-benz       3685.0   3605.0        NaN  3731.0  3750.0
mercury                NaN      NaN     2910.0     NaN     NaN
mitsubishi             NaN      NaN     2377.0  2394.0     NaN
nissan                 NaN   2008.0     2740.0  2238.0  2452.0
peugot                 NaN      NaN        NaN  3143.0  3358.0
plymouth               NaN      NaN     2208.0  2090.0  2535.0
porsche             2800.0   2756.0     2778.0     NaN     NaN
renault                NaN      NaN     2460.0     NaN  2579.0
saab                   NaN      NaN     2724.0  2767.0     NaN
subaru                 NaN      NaN     2137.0  2314.0  2454.0
toyota              2975.0   2585.0     2370.0  2338.0  2708.0
volkswagen          2254.0      NaN     2221.0  2342.0  2563.0
volvo                  NaN      NaN        NaN  3023.0  3078.0

In [53]:
pd.crosstab(df["make"], df["body-style"], normalize=True).head(10)

body-style     convertible  hardtop  hatchback     sedan     wagon
make
alfa-romero       0.009950  0.00000   0.004975  0.000000  0.000000
audi              0.000000  0.00000   0.000000  0.024876  0.004975
bmw               0.000000  0.00000   0.000000  0.039801  0.000000
chevrolet         0.000000  0.00000   0.009950  0.004975  0.000000
dodge             0.000000  0.00000   0.024876  0.014925  0.004975
honda             0.000000  0.00000   0.034826  0.024876  0.004975
isuzu             0.000000  0.00000   0.004975  0.004975  0.000000
jaguar            0.000000  0.00000   0.000000  0.014925  0.000000
mazda             0.000000  0.00000   0.049751  0.034826  0.000000
mercedes-benz     0.004975  0.00995   0.000000  0.019900  0.004975